apiVersion: apps/v1
kind: Deployment
metadata:
  name: cityzen-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cityzen
  template:
    metadata:
      labels:
        app: cityzen
    spec:
      containers:
        - name: cityzen
          image: sham9394/cityzen:latest
          ports:
            - containerPort: 80   
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cityzen-service
spec:
  type: NodePort
  selector:
    app: cityzen
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # Any port 30000â€“32767

